development: &default
  client_id: <%= ENV['CLIENT_ID'] %>
  client_secret: <%= ENV['CLIENT_SECRET'] %>
  username: <%= ENV['USERNAME'] %>
  password: <%= ENV['PASSWORD'] %>
  signature: <%= ENV['SIGNATURE'] %>
  app_id: <%= ENV['APP_ID'] %>
  http_timeout: 40
  mode: <%= ENV['SANDBOX_MODE'] %>
  sandbox_email_address: <%= ENV['SANDBOX_EMAIL'] %>

test:
  <<: *default

  # Credentials for REST APIs
  # client_id: EBWKjlELKMYqRNQ6sYvFo64FtaRLRR5BdHEESmha49TM
  # client_secret: EO422dn3gQLgDbuwqTjzrFgFtaRLRR5BdHEESmha49TM

  # Mode can be 'live' or 'sandbox'
  # mode: sandbox

  # Credentials for Classic APIs
  # app_id: APP-80W284485P519543T
  # username: jb-us-seller_api1.paypal.com
  # password: WX4WTU3S8MY44S7F
  # signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  # sandbox_email_address: Platform.sdk.seller@gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

  # verbose_logging: true

production:
  <<: *default
  # mode: live
  mode: <%= ENV['SANDBOX_MODE'] %>
